GorgeShipping/Areas/Users/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GorgeShipping.Data;
using GorgeShipping.Models;
using GorgeShipping.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GorgeShipping.Controllers
{
    [Area("Users")]
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public UserListViewModel UserListVM { get; set; }
        public UserListViewModel list { get; set; }

        public HomeController(ApplicationDbContext db)
        {
            _db = db;

            UserListVM = new UserListViewModel
            {
                Users = new Models.User(),
                Addresses = new Models.Address(),
                Addresses2 = new Models.Address(),
                TelephoneNumbers = new Models.TelNo(),
                TelephoneNumbers2 = new Models.TelNo()
            };
        }

        public IActionResult Index(Guid? id)
        {
            var lstUser = _db.Users.Include(a => a.TelephoneNumbers).ToList();
            return View(lstUser);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost()
        {
            if (ModelState.IsValid)
            {
                _db.Users.Add(UserListVM.Users);

                UserListVM.Addresses.UserId = UserListVM.Users.id;

                UserListVM.TelephoneNumbers.UserId = UserListVM.Users.id;
                UserListVM.TelephoneNumbers.IsDefault = true;

                _db.TelephoneNumbers.Add(UserListVM.TelephoneNumbers);
                _db.Addresses.Add(UserListVM.Addresses);

                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(UserListVM);
        }

        public async Task<IActionResult> Detail(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserListVM.Users = await _db.Users.FirstOrDefaultAsync(u => u.id == id);

            UserListVM.Addresses = await _db.Addresses.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.Addresses2 = await _db.Addresses.LastOrDefaultAsync(u => u.UserId == id);

            UserListVM.TelephoneNumbers = await _db.TelephoneNumbers.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.TelephoneNumbers2 = await _db.TelephoneNumbers.LastOrDefaultAsync(u => u.UserId == id);


            if (UserListVM.Users == null)
            {
                return NotFound();
            }
            return View(UserListVM);

        }

        public async Task<IActionResult> Print (Guid? id)
        {
            if (id == null)
                return NotFound();

            UserListVM.Users = await _db.Users.FirstOrDefaultAsync(u => u.id == id);

            UserListVM.Addresses = await _db.Addresses.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.Addresses2 = await _db.Addresses.LastOrDefaultAsync(u => u.UserId == id);

            UserListVM.TelephoneNumbers = await _db.TelephoneNumbers.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.TelephoneNumbers2 = await _db.TelephoneNumbers.LastOrDefaultAsync(u => u.UserId == id);


            if (UserListVM.Users == null)
            {
                return NotFound();
            }
            return View(UserListVM);
        }


    }
}

GorgeShipping/Areas/Users/Controllers/TelNumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GorgeShipping.Data;
using GorgeShipping.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GorgeShipping.Areas.Users.Controllers
{
    [Area("Users")]
    public class TelNumberController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public UserListViewModel UserListVM { get; set; }
        public TelNumberController(ApplicationDbContext db)
        {
            _db = db;

            UserListVM = new UserListViewModel
            {
                Users = new Models.User(),
                Addresses = new Models.Address(),
                Addresses2 = new Models.Address(),
                TelephoneNumbers = new Models.TelNo(),
                TelephoneNumbers2 = new Models.TelNo()

            };
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost(Guid id)
        {
            if (ModelState.IsValid)
            {
                UserListVM.TelephoneNumbers.UserId = id;
                _db.TelephoneNumbers.Add(UserListVM.TelephoneNumbers);

                await _db.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            return View(UserListVM);
        }

    }
}

GorgeShipping/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace GorgeShipping.Controllers
{
    public class AddressController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GorgeShipping/Areas/Users/Views/Home/Create.cshtml
@model GorgeShipping.Models.ViewModel.UserListViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <form method="post" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <h2 class="text-info text-center">New Contact</h2>
        <br /><br />
              <div class="row">
                  <div class="col-sm-1"></div>
                  <div class="col-sm-5">
                      <b>Personal Information</b>
                      <hr width=50% size=5 align=left>
                      <div style="background-color:lavenderblush;">
                          <div class="form-group rounded">
                              <div class="col">
                                  <label asp-for="Users.Name"></label>
                              </div>
                              <div class="col">
                                  @(Html.DevExtreme().TextBoxFor(m => m.Users.Name).Width(250).Height(30))
                              </div>
                              <span asp-validation-for="Users.Name" class="text-danger"></span>
                          </div>

                          <div class="form-group">
                              <div class="col">
                                  <label asp-for="Users.Email"></label>
                              </div>
                              <div class="col">
                                  @(Html.DevExtreme().TextBoxFor(m => m.Users.Email).Width(250).Height(30))
                              </div>
                              <span asp-validation-for="Users.Email" class="text-danger"></span>
                          </div>

                          <div class="form-group">
                              <div class="col ">
                                  <label asp-for="TelephoneNumbers.TelNumber"></label>
                              </div>
                              <div class="col ">
                                  @(Html.DevExtreme().TextBoxFor(m => m.TelephoneNumbers.TelNumber).Mask("000-000-0000").Width(200).Height(30))
                              </div>
                              <span asp-validation-for="TelephoneNumbers.TelNumber" class="text-danger"></span>
                          </div>
                          <br />
                      </div>
                  </div>
                  <div class="col-sm-5">
                      <b>Address Information</b>
                      <hr width=50% size=5 align=left>
                      <div style="background-color:lavenderblush;">
                          <div class="form-group rounded">
                              <div class="col">
                                  <label asp-for="Addresses.AddressDetail"></label>
                              </div>
                              <div class="col">
                                  @(Html.DevExtreme().TextAreaFor(m => m.Addresses.AddressDetail).Height(80))
                              </div>
                              <span asp-validation-for="Addresses.AddressDetail" class="text-danger"></span>
                          </div>
                          <div class="col row">
                              <div class="form-group">
                                  <div class="col">
                                      <label asp-for="Addresses.District"></label>
                                  </div>
                                  <div class="col">
                                      @(Html.DevExtreme().TextBoxFor(m => m.Addresses.District).Width(170).Height(30))
                                  </div>
                                  <span asp-validation-for="Addresses.District" class="text-danger"></span>
                              </div>
                              &nbsp; &nbsp;
                              <div class="form-group">
                                  <div class="col">
                                      <label asp-for="Addresses.Province"></label>
                                  </div>
                                  <div class="col">
                                      @(Html.DevExtreme().TextBoxFor(m => m.Addresses.Province).Width(170).Height(30))
                                  </div>
                                  <span asp-validation-for="Addresses.Province" class="text-danger"></span>
                              </div>
                          </div>

                          <div class="form-group">
                              <div class="col">
                                  <label asp-for="Addresses.Code"></label>
                              </div>
                              <div class="col">
                                  @(Html.DevExtreme().TextBoxFor(m => m.Addresses.Code).Mask("00000").Width(170).Height(30))
                              </div>
                              <span asp-validation-for="Addresses.Code" class="text-danger"></span>
                          </div>

                          <div class="form-group">
                              <div class="col">
                                  <label asp-for="Addresses.Note"></label>
                              </div>
                              <div class="col">
                                  @(Html.DevExtreme().TextAreaFor(m => m.Addresses.Note).Height(40))
                              </div><br />
                              <span asp-validation-for="Addresses.Note" class="text-danger"></span>
                          </div>
                      </div>

                      <div class="form-group text-right">
                          <a asp-action="Index" class="btn btn-outline-success">Back</a>
                          <input type="submit" class="btn btn-outline-info" value="Create" />                                                 
                      </div>
                      <div class="col-sm-1"></div>
                  </div>
              </div>
</form>

    @section Scripts{
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

GorgeShipping/Areas/Users/Views/Home/Detail.cshtml
@model GorgeShipping.Models.ViewModel.UserListViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detail</title>
</head>
<body>
    <form method="post" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <h2 class="text-info text-center">Contact Detail</h2>
        <br /><br />
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-5">
                <b>Personal Information</b>
                <hr width=50% size=5 align=left>
                <div style="background-color:lavenderblush;">
                    <div class="form-group rounded">
                        <div class="col">
                            <label asp-for="Users.Name"></label>
                        </div>
                        <div class="col">
                            @(Html.DevExtreme().TextBoxFor(m => m.Users.Name).Width(250).Height(30))
                        </div>
                        <span asp-validation-for="Users.Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <div class="col">
                            <label asp-for="Users.Email"></label>
                        </div>
                        <div class="col">
                            @(Html.DevExtreme().TextBoxFor(m => m.Users.Email).Width(250).Height(30))
                        </div>
                        <span asp-validation-for="Users.Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <div class="col">
                            <h6 class="text-info">First Number</h6>
                            <partial name="_TelPartial" model="@Model.TelephoneNumbers" />
                        </div>
                    </div>
                    <br />

                    @if (Model.TelephoneNumbers.id != Model.TelephoneNumbers2.id)
                    {
                        <div class="form-group">
                            <div class="col">
                                <h6 class="text-info">Second Number</h6>
                                <partial name="_TelPartial" model="@Model.TelephoneNumbers2" />
                            </div>
                        </div>
                    }
                    <br />
                </div>
            </div>

            <div class="col-sm-5">
                <b>Address Information</b>
                <hr width=50% size=5 align=left>
                <div style="background-color:lavenderblush;">

                    <div class="form-group">
                        <div class="col">
                            <h6 class="text-info">First Address</h6>
                            <partial name="_DetailPartial" model="@Model.Addresses" />
                        </div>
                    </div>

                    <br />

                    @if (Model.Addresses.id != Model.Addresses2.id)
                    {
                    <div class="form-group">
                        <div class="col">
                            <h6 class="text-info">Second Address</h6>
                            <partial name="_DetailPartial" model="@Model.Addresses2" />
                        </div>
                    </div>
                    }
                    <br />

                </div>
                <br />
                <div class="form-group">

                    @if (Model.Addresses.id != Model.Addresses2.id && Model.TelephoneNumbers.id != Model.TelephoneNumbers2.id)
                    {
                    <div class="text-center">
                        <a asp-action="Index" class="btn btn-outline-success">Back to List</a>
                        <a asp-action="Print" asp-route-id="@Model.Users.id" class="btn btn-outline-warning">Print</a> 
                    </div>
                    }

                    else if (Model.Addresses.id != Model.Addresses2.id)
                    {
                    <div class="text-center">
                        <a asp-action="Index" class="btn btn-outline-success">Back to List</a>
                        <a asp-controller="TelNumber" asp-action="Create" asp-route-id="@Model.TelephoneNumbers.UserId" class="btn btn-outline-info">
                            <i class="fas fa-phone-alt"></i> &nbsp; New Phone
                            <a asp-action="Print" asp-route-id="@Model.Users.id" class="btn btn-outline-warning">Print</a>
                        </a>
                    </div>
                    }

                    else if (Model.TelephoneNumbers.id != Model.TelephoneNumbers2.id)
                    {
                <div class="text-center">
                    <a asp-controller="Address" asp-action="Create" asp-route-id="@Model.Addresses.UserId" class="btn btn-outline-info">
                        <i class="far fa-address-card"></i> &nbsp; New Address
                    </a>
                    <a asp-action="Index" class="btn btn-outline-success">Back to List</a>
                    <a asp-action="Print" asp-route-id="@Model.Users.id" class="btn btn-outline-warning">Print</a>
                </div>
                    }

                    else
                    {
                <div class="text-center">
                    <a asp-controller="Address" asp-action="Create" asp-route-id="@Model.Addresses.UserId" class="btn btn-outline-info">
                        <i class="far fa-address-card"></i> &nbsp; New Address
                    </a>
                    <a asp-action="Index" class="btn btn-outline-success">Back to List</a>
                    <a asp-controller="TelNumber" asp-action="Create" asp-route-id="@Model.TelephoneNumbers.UserId" class="btn btn-outline-info">
                        <i class="fas fa-phone-alt"></i> &nbsp; New Phone
                    </a> <br />

                    <a asp-action="Print" asp-route-id="@Model.Users.id" class="btn btn-outline-warning">Print</a>
                </div>
                    }
                </div>

                <div class="col-sm-1"></div>
            </div>

        </div>
    </form>

</body>
</html>

GorgeShipping/Areas/Users/Views/Home/Index.cshtml
@using GorgeShipping.Models
@model IEnumerable<GorgeShipping.Models.User>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="form-group row">
        <div class="col-3"></div>
        <div class="col">
            <br />
            <h2 class="text-info text-center">Gorge Shipping</h2>

            <div class="row" style="padding-top:10px">

                <div class="col">

                    <div class="dx-field-label">Find by Phone Number :</div>
                    <br />
                    <div class="active-3 mb-4">
                        <input class="form-control mr-sm-2" type="text" id="Input"
                               onkeyup="function()" placeholder="Search Phone Number" aria-label="Search" />
                    </div>
                    <a asp-action="Index">Back to full List</a>

                </div>

            </div>

            <br />

            <div class="text-justify">
                <a asp-action="Create" class="btn btn-outline-info"> <i class="fas fa-user-plus"></i> &nbsp;New!</a>
            </div>

            <br /> <br />
            <div class="col">
                <table  class="table text-center  table-bordered table-sm">
                    <tr class="table-info table-striped text-center">
                        <th>
                            @Html.DisplayNameFor(m => m.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.FirstOrDefault().TelephoneNumbers.FirstOrDefault().TelNumber)
                        </th>
                        <th>
                            Phone Number 2
                        </th>

                    </tr>


                    @foreach (var user in Model)
                    {
                        <tbody id="myTable">
                            <tr data-href="@Url.Action("Detail/"+user.id)">
                                <td>
                                    @Html.DisplayFor(m => user.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(m => user.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(m => user.TelDefault.TelNumber)
                                </td>
                                @if (user.TelephoneNumbers.LastOrDefault().TelNumber != user.TelDefault.TelNumber)
                                {
                                    <td>
                                        @Html.DisplayFor(m => user.TelephoneNumbers.LastOrDefault().TelNumber)
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                            </tr>
                        </tbody>
                    }
                </table>
            </div>
        </div>
        <div class="col-3"></div>
    </div>

    @*<script>
            function SearchFunction() {
                var input, filter, table, tr, td, i, txtValue;

                input = document.getElementById("myInput");
                table = document.getElementById("myTable");

                filter = input.value.toUpperCase();

                tr = table.getElementsByTagName("tr");

                for (i = 0; i < tr.length; i++) {
                    td = tr[i].getElementsByTagName("td")[2];

                    if (td) {
                        txtValue = td.textContent || td.innerText;
                        if (txtValue.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = "";
                        }
                        else {
                            tr[i].style.display = "none";
                        }
                    }
                }
            }
        </script>*@

    <script>
        $(document).ready(function () {
            $("#Input").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const rows = document.querySelectorAll("tr[data-href]");

            rows.forEach(row => {
                row.addEventListener("click", () => {
                    window.location.href = row.dataset.href;
                });
            })
        });
    </script>

    <style>
        tr[data-href] {
            cursor: pointer;
        }
    </style>
</body>
</html>

GorgeShipping/Areas/Users/Views/Home/Print.cshtml
@model  GorgeShipping.Models.ViewModel.UserListViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Print</title>
</head>
<body>
    <div class="col" style="padding-top:100px; font-size:32px; font-family:'Cordia New'">
        <b>ผู้ส่ง</b>

        <div class="col">
            @Html.DisplayFor(m => m.Users.Name)
        </div>
        <div class="col-6">
            @Html.DisplayFor(m => m.Addresses.AddressDetail)
        </div>
        <div class="col">
            อำเภอ @Html.DisplayFor(m => m.Addresses.District)
            จังหวัด @Html.DisplayFor(m => m.Addresses.Province)
            @Html.DisplayFor(m => m.Addresses.Code)
        </div>

        <div class="col" style="font-size:30px; font-family:'Cordia New'">
            <b>โทรศัพท์</b>
            @Html.DisplayFor(m => m.TelephoneNumbers.TelNumber),
            @Html.DisplayFor(m => m.TelephoneNumbers2.TelNumber)
        </div>
    </div>

    <div class="form row">
        <div class="col-6"></div>
        <div class="col" style="padding-top:20px; font-size:32px; font-family:'Cordia New'">
            <b>ผู้รับ</b>

            <div class="col">
                @Html.DisplayFor(m => m.Users.Name)
            </div>
            <div class="col">
                @Html.DisplayFor(m => m.Addresses.AddressDetail)
            </div>
            <div class="col">
                อำเภอ @Html.DisplayFor(m => m.Addresses.District)
                จังหวัด @Html.DisplayFor(m => m.Addresses.Province)
                @Html.DisplayFor(m => m.Addresses.Code)
            </div>

            <div class="col" style="font-size:30px; font-family:'Cordia New'">
                <b>โทรศัพท์</b>
                @Html.DisplayFor(m => m.TelephoneNumbers.TelNumber),
                @Html.DisplayFor(m => m.TelephoneNumbers2.TelNumber)
            </div>
        </div>
    </div>



    <br /><br />
          <div class="no-print">
              <div class="row text-center" style="margin-left:0px; margin-right:0px;">
                  <div class="col">
                      <a class="btn btn-outline-primary no-print" href="javascript:window.print()">Print</a>
                  </div>
              </div>
          </div>


    <br /><br />
</body>
</html>