GorgeShipping/Areas/Users/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DevExtreme.AspNet.Mvc;
using GorgeShipping.Data;
using GorgeShipping.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GorgeShipping.Controllers
{
    [Area("Users")]
    public class ListController : Controller
    {

        private readonly ApplicationDbContext _db;

        [BindProperty]
        public UserListViewModel UserListVM { get; set; }
        public ListController(ApplicationDbContext db)
        {
            _db = db;

            UserListVM = new UserListViewModel
            {
                Users = new Models.User(),
                Addresses = new Models.Address(),
                Addresses2 = new Models.Address(),
                TelephoneNumbers = new Models.TelNo(),
                TelephoneNumbers2 = new Models.TelNo()
            };
        }


        public IActionResult Index()
        {
            var lstUser = _db.Users.Include(a => a.Addresses).Include(a => a.TelephoneNumbers).ToList();
            return View(lstUser);

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(UserListVM);
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost()
        {
            if (ModelState.IsValid)
            {
                _db.Users.Add(UserListVM.Users);

                UserListVM.Addresses.UserId = UserListVM.Users.id;
                UserListVM.TelephoneNumbers.UserId = UserListVM.Users.id;


                UserListVM.TelephoneNumbers.IsDefault = true;

                _db.Addresses.Add(UserListVM.Addresses);
                _db.TelephoneNumbers.Add(UserListVM.TelephoneNumbers);


                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(UserListVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserListVM.Users = await _db.Users.SingleOrDefaultAsync(u => u.id == id);

            UserListVM.TelephoneNumbers = await _db.TelephoneNumbers.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.TelephoneNumbers2 = await _db.TelephoneNumbers.LastOrDefaultAsync(u => u.UserId == id);

            UserListVM.Addresses = await _db.Addresses.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.Addresses2 = await _db.Addresses.LastOrDefaultAsync(u => u.UserId == id);


            if (UserListVM.Users == null)
            {
                return NotFound();
            }
            return View(UserListVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        //POST Edit Action  Method
        public async Task<IActionResult> Edit(Guid id)
        {
            if (ModelState.IsValid)
            {
                var userFromDb = _db.Users.Where(m => m.id == UserListVM.Users.id).FirstOrDefault();
                var TelFromDb = _db.TelephoneNumbers.Where(m => m.UserId == UserListVM.Users.id).FirstOrDefault();
                var AddrFromDb = _db.Addresses.Where(m => m.UserId == UserListVM.Users.id).FirstOrDefault();
                var Tel2FromDb = _db.TelephoneNumbers.Where(m => m.UserId == UserListVM.Users.id).LastOrDefault();
                var Addr2FromDb = _db.Addresses.Where(m => m.UserId == UserListVM.Users.id).LastOrDefault();
                               
                userFromDb.Name = UserListVM.Users.Name;
                userFromDb.Email = UserListVM.Users.Email;
                TelFromDb.TelNumber = UserListVM.TelephoneNumbers.TelNumber;
                AddrFromDb.AddressDetail = UserListVM.Addresses.AddressDetail;
                AddrFromDb.District = UserListVM.Addresses.District;
                AddrFromDb.Province = UserListVM.Addresses.Province;
                AddrFromDb.Code = UserListVM.Addresses.Code;
                AddrFromDb.Note = UserListVM.Addresses.Note;

                if (UserListVM.TelephoneNumbers2 != null)
                {
                    Tel2FromDb.TelNumber = UserListVM.TelephoneNumbers2.TelNumber;
                }


                if (UserListVM.Addresses2 != null)
                {

                    Addr2FromDb.AddressDetail = UserListVM.Addresses2.AddressDetail;
                    Addr2FromDb.District = UserListVM.Addresses2.District;
                    Addr2FromDb.Province = UserListVM.Addresses2.Province;
                    Addr2FromDb.Code = UserListVM.Addresses2.Code;
                    Addr2FromDb.Note = UserListVM.Addresses2.Note;

                }


                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(UserListVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserListVM.Users = await _db.Users.SingleOrDefaultAsync(u => u.id == id);

            UserListVM.TelephoneNumbers = await _db.TelephoneNumbers.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.TelephoneNumbers2 = await _db.TelephoneNumbers.LastOrDefaultAsync(u => u.UserId == id);

            UserListVM.Addresses = await _db.Addresses.FirstOrDefaultAsync(u => u.UserId == id);
            UserListVM.Addresses2 = await _db.Addresses.LastOrDefaultAsync(u => u.UserId == id);


            if (UserListVM.Users == null)
            {
                return NotFound();
            }
            return View(UserListVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        //POST Delete Action  Method
        public async Task<IActionResult> Delete(Guid id)
        {
            var lstUser = await _db.Users.FindAsync(id);

            _db.Users.Remove(lstUser);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

    }
}

GorgeShipping/Views/Shared/_DetailPartial.cshtml
@model GorgeShipping.Models.Address

<div>
    <div class="form-group rounded">
        <div class="col">
            @*<label asp-for="AddressDetail"></label>*@
        </div>
        <div class="col">
            @(Html.DevExtreme().TextAreaFor(m => m.AddressDetail).Height(80).ReadOnly(true))
        </div>
    </div>

    <div class="col row">
        <div class="form-group">
            <div class="col">
                <label asp-for="District"></label>
            </div>
            <div class="col">
                @(Html.DevExtreme().TextBoxFor(m => m.District).Width(200).Height(30).ReadOnly(true))
            </div>
        </div>
        &nbsp; &nbsp;
        <div class="form-group">
            <div class="col">
                <label asp-for="Province"></label>
            </div>
            <div class="col">
                @(Html.DevExtreme().TextBoxFor(m => m.Province).Width(200).Height(30).ReadOnly(true))
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col">
            <label asp-for="Code"></label>
        </div>
        <div class="col">
            @(Html.DevExtreme().TextBoxFor(m => m.Code).Mask("00000").Width(200).Height(30).ReadOnly(true))
        </div>
    </div>

    <div class="form-group">
        <div class="col">
            <label asp-for="Note"></label>
        </div>
        <div class="col">
            @(Html.DevExtreme().TextAreaFor(m => m.Note).Height(50).ReadOnly(true))
        </div><br />
    </div>

</div>

GorgeShipping/Views/Shared/_EditPartial.cshtml
@model GorgeShipping.Models.Address


<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group row">
    <div class="col-3">
        <label asp-for="AddressDetail"></label>
    </div>
    <div class="col">
        <input asp-for="AddressDetail" class="form-control" />
    </div>
    <span asp-validation-for="AddressDetail" class="text-danger"></span>
</div>

<div class="form-group row">
    <div class="col-3">
        <label asp-for="District"></label>
    </div>
    <div class="col">
        <input asp-for="District" class="form-control" />
    </div>
    <span asp-validation-for="District" class="text-danger"></span>
</div>

<div class="form-group row">
    <div class="col-3">
        <label asp-for="Province"></label>
    </div>
    <div class="col">
        <input asp-for="Province" class="form-control" />
    </div>
    <span asp-validation-for="Province" class="text-danger"></span>
</div>

<div class="form-group row">
    <div class="col-3">
        <label asp-for="Code"></label>
    </div>
    <div class="col">
        <input asp-for="Code" class="form-control" />
    </div>
    <span asp-validation-for="Code" class="text-danger"></span>
</div>

<div class="form-group row">
    <div class="col-3">
        <label asp-for="Note"></label>
    </div>
    <div class="col">
        <input asp-for="Note" class="form-control" />
    </div>
    <span asp-validation-for="Note" class="text-danger"></span>
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GorgeShipping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GorgeShipping</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    <script src="~/js/devextreme/cldr.js"></script>
    <script src="~/js/devextreme/cldr/event.js"></script>
    <script src="~/js/devextreme/cldr/supplemental.js"></script>
    <script src="~/js/devextreme/cldr/unresolved.js"></script>

    <script src="~/js/devextreme/globalize.js"></script>
    <script src="~/js/devextreme/globalize/message.js"></script>
    <script src="~/js/devextreme/globalize/number.js"></script>
    <script src="~/js/devextreme/globalize/currency.js"></script>
    <script src="~/js/devextreme/globalize/date.js"></script>

    @* JSZip for client side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/vectormap-data/world.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="https://kit.fontawesome.com/5309500501.js"></script>  @*add icon*@
</head>

<body>
    
    <partial name="_NavbarPartial" />
    
    <main role="main" class="container">
        @RenderBody()
        @RenderSection("Scripts", required: false)
    </main>
</body>

</html>

GorgeShipping/Views/Shared/_NavbarPartial.cshtml
<nav class="navbar navbar-light bg-light fixed-top navbar-expand-md">
    <a class="navbar-brand" style="font-size:25px;" asp-controller="Home" asp-action="Index">Gorge Shipping</a>

    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id ="navbar" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item" style="padding-left:10px; font-size:20px;"> <a class="nav-link" asp-area="Users" asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="nav-item" style="padding-left:10px; font-size:20px;"> <a class="nav-link" asp-area="Users" asp-controller="List" asp-action="Index">List</a></li>
        </ul>
    </div>
</nav>


  

GorgeShipping/Views/Shared/_TableButtonPartial.cshtml
@model Guid
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td>
    <div class="btn-group">
        &nbsp;
        <div>

            <a type="button" class="btn btn-outline-warning" style="background-color:aliceblue" href="@Url.Action("Edit/"+Model)">
                <i class="fas fa-user-edit"></i>
            </a>
        </div>&nbsp;&nbsp;
        <div>
            <a type="button" class="btn btn-outline-danger" style="background-color:aliceblue" href="@Url.Action("Delete/"+Model)">
                <i class="fas fa-user-minus"></i>
            </a>
        </div>
    </div>
</td>

GorgeShipping/Views/Shared/_TelEditPartial.cshtml
@model GorgeShipping.Models.TelNo

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<div class="form-group rounded">
    <div class="col">
        <label asp-for="TelNumber"></label>
    </div>
    <div class="col">
        @(Html.DevExtreme().TextBoxFor(m => m.TelNumber).Mask("000-000-0000").Width(200).Height(30))
    </div>
    <span asp-validation-for="TelNumber" class="text-danger"></span>
    <br />
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GorgeShipping/Views/Shared/_TelPartial.cshtml
@model GorgeShipping.Models.TelNo

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<div class="form-group rounded">
    <div class="col">
        @*<label asp-for="TelNumber"></label>*@
    </div>
    <div class="col">
        @(Html.DevExtreme().TextBoxFor(m => m.TelNumber).Mask("000-000-0000").Width(200).Height(30).ReadOnly(true))
    </div>
    <span asp-validation-for="TelNumber" class="text-danger"></span>
    <br />
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}